[package]
name = "mostro-chat-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
nostr-sdk = { version = "0.40.0", features = ["nip44", "nip59"] }
clap = { version = "4.5.32", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
